name: neugent art
favicon: null
layout_spectrum: 0.24191
typography_spectrum: 0.75625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf4dc'
    - '#a9b392'
    - '#171717'
    - '#5d593b'
    - '#527091'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.2364044119603932
  rhythmicContrast: 0.6120086740702391
purpose: []
